articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('question/', views.question, name='question'),
    path('nextpage/', views.nextPage, name='nextpage'),
    path('result/<mbti>', views.result, name='result'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.

# 질문 모델
class Question(models.Model):
    question = models.TextField(max_length=100) # 질문
    answer1 = models.TextField(max_length=100) # 답변1
    answer1_letter = models.CharField(max_length=1, blank=True, null=True) # 답변에 따른 알파벳
    answer2 = models.TextField(max_length=100) # 답변2
    answer2_letter = models.CharField(max_length=1, blank=True, null=True) # 답변에 따른 알파벳


# 인물 모델
class Type(models.Model):
    person = models.CharField(max_length=100)
    verse = models.TextField(max_length=100)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    personality = models.TextField(max_length=300, blank=True)
    like = models.TextField(max_length=50, blank=True)
    dislike = models.TextField(max_length=50, blank=True)
    # good_match & bad_match 이미지 링크 넣어서 나중에 불러오기
    good_match_img = models.ImageField(upload_to='images', null=True, blank=True)
    good_match = models.CharField(max_length=10, blank=True)
    bad_match_img = models.ImageField(upload_to='images', null=True, blank=True)
    bad_match = models.CharField(max_length=10, blank=True)
    mbti = models.CharField(max_length=10)

articles/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Type, Question

# Create your views here.
def index(request):
    context = {}
    return render(request, 'articles/index.html', context)

@csrf_exempt
def question(request):
    question = Question.objects.get(pk=1)
    mbti = ''
    context = { # 스크립트에서 쓸 수 있도록 질문모델의 필드값들을 보냄
        'question_pk': question.pk,
        'question': question.question,
        'question_ans1': question.answer1,
        'question_letter1': question.answer1_letter,
        'question_ans2': question.answer2,
        'question_letter2': question.answer2_letter,
        'mbti': mbti,
    }
    return render(request, 'articles/question.html', context)
        
@csrf_exempt
def nextPage(request):
    pk = request.POST.get('pk')
    letter = request.POST.get('letter')
    mbti = request.POST.get('mbti')
    pk = int(pk) + 1
    mbti += letter
    question = Question.objects.get(pk=pk)
    data = {
        'question_pk': question.pk,
        'question': question.question,
        'question_ans1': question.answer1,
        'question_ans2': question.answer2,
        'question_letter1': question.answer1_letter,
        'question_letter2': question.answer2_letter,
        'mbti': mbti,
    }
    return JsonResponse(data)
        

def result(request, mbti):
    types = Type.objects.all()
    
    first = {}
    second = {}
    third = {}
    fourth = {}
    result = ''
    
    first['I'] = mbti.count('I') # first['I'] == key / mbti.count('I') == value / ex: {'I': 1, 'E': 2}
    first['E'] = mbti.count('E') # first['E'] == key / mbti.count('E') == value / ex: {'I': 1, 'E': 2}
    key = max(first, key=first.get) # key = max(dict_name, key=dict_name.get)
    result += key # result += max_value를 가지는 key(ex: 'E')
    
    second['S'] = mbti.count('S')
    second['N'] = mbti.count('N')
    key = max(second, key=second.get)
    result += key
    
    third['T'] = mbti.count('T')
    third['F'] = mbti.count('F')
    key = max(third, key=third.get)
    result += key

    fourth['P'] = mbti.count('P')
    fourth['J'] = mbti.count('J')
    key = max(fourth, key=fourth.get)
    result += key
    
    for type in types:
        if type.mbti == result:
            result_type = Type.objects.get(mbti=type.mbti)
            break
    
    context = {
        'result_type': result_type,
    }
    
    return render(request, 'articles/result.html', context)

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <div class="d-flex row text-center justify-content-center">
      <div class="bible_title">
        <h2 class="index-title my-5">나와
          <span class="title-highlight">닮은</span>
          성경 인물 테스트</h2>
      </div>
      <div class="move_ani">
        <img class="index-img my-2" src="{% static 'images/index_img.png' %}" alt="index page img">
        <div>
          <button class="index-btn my-5" type="button" onclick="location.href='{% url 'articles:question' %}'">시작하기</button>
        </div>
      </div>
    </div>
{% comment %} 
  <script src="{% static 'js/data.js' %}"></script>
  <script src="{% static 'js/start.js' %}"></script> {% endcomment %}
{% endblock content %}

articles/templates/articles/question.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/question.css' %}">
    <link rel="icon" href="{% static 'images/bible_favicon.png' %}">
    <title>성경 인물 테스트</title>
  </head>

  <body>
    <div class="main container text-center">
      <div class="progress mx-auto mt-5">
        <div class="progress-bar" role="progressbar" aria-label="Basic example" style="background-color: #B70048; border-radius: 20px; width: 8.3%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      <h1 class="question-tag mt-3">
        <span id="question-progress">{{ question_pk }}</span>
        / 12</h1>
      <div class="question my-5" id="question">{{ question }}</div>
      <button type="button" class="choice my-4" id="choice1" data-letter="{{ question_letter1 }}" data-mbti="{{ mbti }}" data-value="{{ question_pk }}">{{ question_ans1 }}</button>
      <button type="button" class="choice my-4" id="choice2" data-letter="{{ question_letter2 }}" data-mbti="{{ mbti }}" data-value="{{ question_pk }}">{{ question_ans2 }}</button>
    </div>
  </body>

  <div class="loader container text-center" style="display:none;">
    <img class="loading-gif mb-5" src="{% static 'images/bible_mbti_loader.gif' %}" alt="">
    <h1 class="loading-phrase">닮은 인물을 찾는 중이에요...</h1>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
  <script>
    $('.choice').click(function (event) {
      var progress = document.querySelector('.progress-bar');
      progress.style.width = (100 / 12) * (pk + 1) + '%';
      var chosenId = event.target.id
      var pk = $(`#${chosenId}`).data('value') // pk
      var letter = $(`#${chosenId}`).data('letter') // 답변에 해당하는 알파벳
      var mbti = $(`#${chosenId}`).data('mbti') // mbti 합쳐진것..?

      $.ajax({
        url: '/nextpage/', // 클릭할때마다 url에 해당하는 views가 작동됨
        dataType: "json",
        type: "POST",
        data: {
          'pk': pk,
          'letter': letter,
          'mbti': mbti
        },
        success: function (data) {
          console.log('success')
          var progress = document.querySelector('.progress-bar');
          progress.style.width = (100 / 12) * (pk + 1) + '%';
          $('#question-progress').text(data['question_pk'])
          $('#question').text(data['question'])
          $('#choice1').text(data['question_ans1'])
          $('#choice1').data('value', data['question_pk'])
          $('#choice1').data('letter', data['question_letter1'])
          $('#choice1').data('mbti', data['mbti'])
          $('#choice2').text(data['question_ans2'])
          $('#choice2').data('value', data['question_pk'])
          $('#choice2').data('letter', data['question_letter2'])
          $('#choice2').data('mbti', data['mbti'])
        },
        error: function (request, status, error) {
          console.log('finished')
          $("div.main").css('display', 'none')
          $("div.loader").css('display', 'block')
          mbti += letter
          setTimeout(() => {
            window.location.href = `/result/${mbti}`
          }, 3500)
        }
      });
    })
  </script>

</html>

articles/templates/articles/question_.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/question.css' %}">
  <div class="container">
    <div class="progress mt-5">
      <div class="progress-bar" role="progressbar" aria-label="Basic example" style="width: 75%; background-color: #B70048;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="text-center mt-3">
      <p class="main_font">10&nbsp/&nbsp12</p>
    </div>
    <div class="text-center">
      <p class="my-5 pt-5 question">교회 수련회가 열린대! 하지만 아는 사람이 없는 나는?</p>
    </div>
    <div class="text-center d-flex justify-content-center row mt-5 pt-5">
      <div class="answer">
        <p class="answer_p">아는 사람 하나도 없는데...다음에 간다고 한다.</p>
      </div>
      <div class="answer mt-5">
        <p class="answer_p">교회 친구들도 많이 사귀고 재밌겠다!</p>
      </div>
    </div>
    <div class="qBox"></div>
    <div class="answerBox"></div>
  </div>
  <script src="{% static 'js/data.js' %}"></script>
  <script src="{% static 'js/start.js' %}"></script>
{% endblock content %}

articles/templates/articles/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/result.css' %}">
  <div class="container text-center" id="result">
    <div class="text-center">
      <p class="index-title mt-5 fw-bold lh-1">나와
        <span class="title-highlight">닮은</span>
        성경 인물은</p>
     <p class="fw-bold lh-1 mb-0">{{ result_type.verse }},</p>
      <p><span class="title-highlight lh-1"></span>{{ result_type.person }}<span class="title-highlight"></span></p>
      <img class="mb-4 w-50 rounded-5 resultimg" src="{{ result_type.image.url }}" alt="">
      <div class="d-flex justify-content-center">
        
        <h4 class="personality  text-center"><div class="text-start"><p class="p_highlight text-center">{{ result_type.person }} 닮은 나의 성격은?</p></div>{% autoescape off %}{{ result_type.personality}}{% endautoescape %}</h4>
      </div>
      {% comment %} <div class="my-5">{{ result_type.image }}</div> {% endcomment %}
      
      {% comment %} <h4 class="my-5 w-50 m-auto text-start">{{ result_type.personality }}</h4> {% endcomment %}
      <div class="good_bad_font ">
        <div class="my-3"> <span class="p_highlight">좋아하는 것</span><br>{{result_type.like}}</div>
        <div> <span class="p_highlight">싫어하는 것</span> <br>{{result_type.dislike}}</div>
      </div>
      <hr class="line_under">
      <div class="d-flex justify-content-center my-4">
        <div class="mx-3">
          <h2 class="mb-3 fw-bold" style="font-size: 15px;">잘맞는 유형</h2>
          {% comment %} <div class="mb-4">{{ result_type.good_match_img.url }}임시이미지</div> {% endcomment %}
          <img class="good_bad mb-2 rounded-5" src="{{ result_type.good_match_img.url }}" alt="">
          <h5 class="end_t fw-bold" style="font-size: 15px;">{{ result_type.good_match}}</h5>
        </div>
        <div class="mx-3">
          <h2 class="mb-3 fw-bold" style="font-size: 15px;">안맞는 유형</h2>
          {% comment %} <div class="mb-4">{{ result_type.bad_match_img }}임시이미지</div> {% endcomment %}
          <img class="good_bad mb-2 rounded-5" src="{{ result_type.bad_match_img.url }}" alt="">
          <h5 class="end_t fw-bold" style="font-size: 15px;">{{ result_type.bad_match}}</h5>
        </div>
      </div>
      <button class="restart-btn" onclick="location.href='{% url 'articles:question' %}'">다시하기</button>
      <div class="my-2">
        <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <div class="addthis_inline_share_toolbox_iwnx"></div>
      </div>
    </div>
    {% comment %} <div class="d-flex row text-center justify-content-center">
      <h1 class="index-title my-5">당신의
        <span class="title-highlight">결과</span>
        는?</h1>
      <div class="resultname">{{result_type.person}}</div>
      <div class="resultmbti">{{result_type.mbti}}</div>
      <img class="index-img my-2" src="{% static 'images/index_img.png' %}" alt="index page img">
      <div class="resultDesc">{{result_type.verse}}</div>
      <div>
        <button class="index-btn my-5" type="button">공유하기</button>

        <!-- Go to www.addthis.com/dashboard to customize your tools -->
        <div class="addthis_inline_share_toolbox_iwnx"></div>

      </div>
    </div> {% endcomment %}
  </div>
  <!-- Go to www.addthis.com/dashboard to customize your tools -->
  <script script="script" type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-639882a381a3781a"></script>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>성경 인물 테스트</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com/%22%3E">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="crossorigin">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@900&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'images/bible_favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>

  <body>
    {% block content %}{% endblock content %}

  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

</html>